baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Knowledge Hub'

[taxonomies]
  tag = "tags"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 5

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
